## Numpy

### Numpy Library

In [1]:
# Import numpy before using it
import numpy as np

In [2]:
# array metho from numpy
x = np.array([1, 2, 3, 4])

In [3]:
x

array([1, 2, 3, 4])

In [5]:
# To create an array of 5 zeros
np.zeros(5)

# Array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# random floating point numbers between 0 - 1
np.random.random(5)

array([0.39766754, 0.08247479, 0.55519452, 0.11357467, 0.51074649])

### 1-D Operations

In [7]:
# Create two arrays
new_math = np.array([1, 2, 3])
new_one = np.ones(3)

new_math + new_one

array([2., 3., 4.])

In [10]:
# Multiply the first array by 4 and the second one by 10
new_math * 4

array([ 4,  8, 12])

In [11]:
new_one * 10

array([10., 10., 10.])

In [12]:
# Python arrays are zero indexed
new_math[0]

1

In [13]:
new_math[-1]

3

In [14]:
# math 1-D functions
new_math.max()

3

In [15]:
new_math.sum()

6

#### N-D Arrays or Matrices

In [17]:
x = np.array([[10, 20], [30, 40]])

In [18]:
x

array([[10, 20],
       [30, 40]])

In [19]:
np.ones((3, 4)) # first attribute rows and second is columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.random.random((3, 4))

array([[0.3165324 , 0.04022002, 0.85844362, 0.08417195],
       [0.67745488, 0.60351726, 0.31797274, 0.9050313 ],
       [0.94528629, 0.54160956, 0.43717413, 0.79959488]])

In [22]:
y = np.array([[2,4],[5,6]])

In [23]:
x + y

array([[12, 24],
       [35, 46]])

In [24]:
# Multipling arrays
x.dot(y)

array([[120, 160],
       [260, 360]])

In [27]:
# Indexing: arrayName[row, columen]
y[0, 1]

4

In [28]:
x[1, 1]

40

In [29]:
# Accessing many items 
y[0:2, 1]

array([4, 6])

 ### Reshaping Arrays

In [30]:
new_data = np.array([1, 2, 3, 4, 5, 6])
new_data.reshape(2, 3) #Args: row, col

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
new_data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
# Creating multi-dimensional array
x = np.array([[[10, 20]], [[3, 40]],[[30, 70]], [[60, 50]]])

In [37]:
x

array([[[10, 20]],

       [[ 3, 40]],

       [[30, 70]],

       [[60, 50]]])

In [38]:
# Creating a multi-dimensional array of ones
np.zeros((5, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])