## Numpy

### Numpy Library

In [1]:
# Import numpy before using it
import numpy as np

In [2]:
# array metho from numpy
x = np.array([1, 2, 3, 4])

In [3]:
x

array([1, 2, 3, 4])

In [5]:
# To create an array of 5 zeros
np.zeros(5)

# Array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# random floating point numbers between 0 - 1
np.random.random(5)

array([0.39766754, 0.08247479, 0.55519452, 0.11357467, 0.51074649])